class TransactionPool:
    def __init__(self):
        self.transaction_map = {}

    def set_transaction(self, transaction):
        """
        Set a transaction in the transaction pool.
        """
        self.transaction_map[transaction.id] = transaction

    def existing_transaction(self, address):
        """
        Find a transaction generated by the address in the transaction pool
        """
        for transaction in self.transaction_map.values():
            if transaction.input['address'] == address:
                return transaction

    def transaction_data(self):
        """
        Return the transactions of the transaction pool represented in their json serialized format
        """
        return list(
            map(
                lambda transacton: transacton.to_json(), 
                self.transaction_map.values()
            )
        )

    def clear_blockchain_transaction(self, blockchain):
        """
        Clear the transaction pool of any transactions that are already in the blockchain
        """
        for block in blockchain.chain:
            for transaction in block.data:
                try:
                    del self.transaction_map[transaction['id']]
                except KeyError:
                    pass